// <auto-generated />
using System;
using DevFlowMonitor.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevFlowMonitor.Api.Data.Migrations
{
    [DbContext(typeof(DevFlowDbContext))]
    partial class DevFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("devflow")
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.Attempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Conclusion")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("WorkflowRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowRunId", "Number")
                        .IsUnique();

                    b.ToTable("attempts", "devflow");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.GitCommit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("AuthorName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("AuthoredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sha")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "Sha")
                        .IsUnique();

                    b.ToTable("commits", "devflow");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.GitHubAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSynchronizedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Owner")
                        .IsUnique();

                    b.ToTable("github_accounts", "devflow");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.GitHubUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("ExternalId")
                        .HasColumnType("bigint");

                    b.Property<string>("HtmlUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Login");

                    b.ToTable("users", "devflow");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Conclusion")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<long>("ExternalId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RunnerName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("AttemptId", "ExternalId")
                        .IsUnique();

                    b.HasIndex("AttemptId", "Name");

                    b.ToTable("jobs", "devflow");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.Metric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dimension")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("SampleSize")
                        .HasColumnType("integer");

                    b.Property<string>("ScopeKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("WorkflowId");

                    b.HasIndex("AccountId", "ScopeKey", "PeriodStart", "PeriodEnd", "Kind", "Dimension")
                        .IsUnique();

                    b.ToTable("metrics", "devflow");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultBranch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long>("ExternalId")
                        .HasColumnType("bigint");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(201)
                        .HasColumnType("character varying(201)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "ExternalId")
                        .IsUnique();

                    b.HasIndex("AccountId", "FullName")
                        .IsUnique();

                    b.ToTable("repositories", "devflow");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.Step", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Conclusion")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Number")
                        .IsUnique();

                    b.ToTable("steps", "devflow");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.TriggerEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "Name")
                        .IsUnique();

                    b.ToTable("events", "devflow");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<long>("ExternalId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Path")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "ExternalId")
                        .IsUnique();

                    b.ToTable("workflows", "devflow");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.WorkflowRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("CommitId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Conclusion")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid");

                    b.Property<long>("ExternalId")
                        .HasColumnType("bigint");

                    b.Property<string>("HtmlUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("RunNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("CommitId");

                    b.HasIndex("EventId");

                    b.HasIndex("WorkflowId", "ExternalId")
                        .IsUnique();

                    b.HasIndex("WorkflowId", "StartedAt");

                    b.ToTable("workflow_runs", "devflow");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.Attempt", b =>
                {
                    b.HasOne("DevFlowMonitor.Api.Data.Entities.WorkflowRun", "WorkflowRun")
                        .WithMany("Attempts")
                        .HasForeignKey("WorkflowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowRun");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.GitCommit", b =>
                {
                    b.HasOne("DevFlowMonitor.Api.Data.Entities.Repository", "Repository")
                        .WithMany("Commits")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.Job", b =>
                {
                    b.HasOne("DevFlowMonitor.Api.Data.Entities.Attempt", "Attempt")
                        .WithMany("Jobs")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attempt");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.Metric", b =>
                {
                    b.HasOne("DevFlowMonitor.Api.Data.Entities.GitHubAccount", "Account")
                        .WithMany("Metrics")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevFlowMonitor.Api.Data.Entities.Repository", "Repository")
                        .WithMany("Metrics")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DevFlowMonitor.Api.Data.Entities.Workflow", "Workflow")
                        .WithMany("Metrics")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Account");

                    b.Navigation("Repository");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.Repository", b =>
                {
                    b.HasOne("DevFlowMonitor.Api.Data.Entities.GitHubAccount", "Account")
                        .WithMany("Repositories")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.Step", b =>
                {
                    b.HasOne("DevFlowMonitor.Api.Data.Entities.Job", "Job")
                        .WithMany("Steps")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.TriggerEvent", b =>
                {
                    b.HasOne("DevFlowMonitor.Api.Data.Entities.Repository", "Repository")
                        .WithMany("Events")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.Workflow", b =>
                {
                    b.HasOne("DevFlowMonitor.Api.Data.Entities.Repository", "Repository")
                        .WithMany("Workflows")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.WorkflowRun", b =>
                {
                    b.HasOne("DevFlowMonitor.Api.Data.Entities.GitHubUser", "Actor")
                        .WithMany("Runs")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DevFlowMonitor.Api.Data.Entities.GitCommit", "Commit")
                        .WithMany("Runs")
                        .HasForeignKey("CommitId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DevFlowMonitor.Api.Data.Entities.TriggerEvent", "Event")
                        .WithMany("Runs")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DevFlowMonitor.Api.Data.Entities.Workflow", "Workflow")
                        .WithMany("Runs")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Commit");

                    b.Navigation("Event");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.Attempt", b =>
                {
                    b.Navigation("Jobs");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.GitCommit", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.GitHubAccount", b =>
                {
                    b.Navigation("Metrics");

                    b.Navigation("Repositories");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.GitHubUser", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.Job", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.Repository", b =>
                {
                    b.Navigation("Commits");

                    b.Navigation("Events");

                    b.Navigation("Metrics");

                    b.Navigation("Workflows");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.TriggerEvent", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.Workflow", b =>
                {
                    b.Navigation("Metrics");

                    b.Navigation("Runs");
                });

            modelBuilder.Entity("DevFlowMonitor.Api.Data.Entities.WorkflowRun", b =>
                {
                    b.Navigation("Attempts");
                });
#pragma warning restore 612, 618
        }
    }
}
